#pragma once

namespace Engine
{
	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };

	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum COMPONENTTYPE { COM_RENDERER, COM_VIBUFFER, COM_SHADER, COM_TRANSFORM, COM_TEXTURE, COM_MODEL, COMPONENTTYPE_END };
}